<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" /><meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>duHast.Revit.Common.Geometry package &#8212; Sample Code Revit Batch Processor 0.1.1 documentation</title>
    <link rel="stylesheet" type="text/css" href="../_static/pygments.css" />
    <link rel="stylesheet" type="text/css" href="../_static/css/adctheme.css" />
    <script data-url_root="../" id="documentation_options" src="../_static/documentation_options.js"></script>
    <script src="../_static/doctools.js"></script>
    <script src="../_static/sphinx_highlight.js"></script>
    <meta name="generator" content="Sphinx/ADC Theme by Mirounga www.mirounga.fr"/>
    <link rel="index" title="Index" href="../genindex.html" />
    <link rel="search" title="Search" href="../search.html" />
    <link rel="top" title="Sample Code Revit Batch Processor 0.1.1 documentation" href="../index.html" />
    <link rel="up" title="duHast.Revit.Common package" href="duHast.Revit.Common.html" />
    <link rel="next" title="duHast.Revit.Common.Objects package" href="duHast.Revit.Common.Objects.html" />
    <link rel="prev" title="duHast.Revit.Common package" href="duHast.Revit.Common.html" />
    <link media="only screen and (max-device-width: 480px)" href="../_static/css/mobile.css" type="text/css" rel="stylesheet" /> 
  </head><body>
<div id="docstitle">
    <p>Sample Code Revit Batch Processor 0.1.1 documentation</p>
</div>
<div id="header">
    <div id="title"><h1>duHast.Revit.Common.Geometry package</h1></div>
    <ul id="headerButtons">
        <li id="toc_button"><div class="headerButton"><a href="#">Table of Contents</a></div></li>
        <li id="page_buttons">
            <div class="headerButton"><a href="../genindex.html" title="General Index" accesskey="I">index</a></div>
            <div class="headerButton"><a href="../py-modindex.html" title="Python Module Index" >modules</a></div>
            <div class="headerButton"><a href="duHast.Revit.Common.Objects.html" title="duHast.Revit.Common.Objects package" accesskey="N">next</a></div>
            <div class="headerButton"><a href="duHast.Revit.Common.html" title="duHast.Revit.Common package" accesskey="P">previous</a></div>
        </li>
    </ul>
</div>

<div id="sphinxsidebar">
  <div class="sphinxsidebarwrapper">
        <ul><li class="toctree-l1"><a href="../index.html">Main Page</a></li></ul>
        <p class="caption" role="heading"><span class="caption-text">Contents:</span></p>
<ul class="current">
<li class="toctree-l1 current"><a class="reference internal" href="modules.html">duHast</a><ul class="current">
<li class="toctree-l2 current"><a class="reference internal" href="duHast.html">duHast package</a><ul class="current">
<li class="toctree-l3 current"><a class="reference internal" href="duHast.html#subpackages">Subpackages</a><ul class="current">
<li class="toctree-l4"><a class="reference internal" href="duHast.Data.html">duHast.Data package</a></li>
<li class="toctree-l4 current"><a class="reference internal" href="duHast.Revit.html">duHast.Revit package</a></li>
<li class="toctree-l4"><a class="reference internal" href="duHast.UI.html">duHast.UI package</a></li>
<li class="toctree-l4"><a class="reference internal" href="duHast.Utilities.html">duHast.Utilities package</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="duHast.html#module-duHast">Module contents</a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="../flows/index.html">Flows</a></li>
</ul>

      <h3>This Page</h3>
      <ul class="this-page-menu">
        <li><a href="../_sources/duHast/duHast.Revit.Common.Geometry.rst.txt"
               rel="nofollow">Show Source</a></li>
      </ul>
    <div id="searchbox" style="display: none">
        <form class="search" action="../search.html" method="get">
                        <div class="search-wrapper">
                        <input type="submit" value="" class="search-left"/>
                        <input class="prettysearch" type="text" name="q" size="18" title="Enter search terms or a module, class or function name."/>
                        <span class="search-right">&nbsp;</span>
                        </div>
          <input type="hidden" name="check_keywords" value="yes" />
          <input type="hidden" name="area" value="default" />
        </form>
    </div>
    <script type="text/javascript">$('#searchbox').show(0);</script>
  </div>
</div>



    <div class="document">
      <div class="documentwrapper">
        <div class="bodywrapper">
          <div class="body">
            
  <section id="duhast-revit-common-geometry-package">
<h1>duHast.Revit.Common.Geometry package<a class="headerlink" href="#duhast-revit-common-geometry-package" title="Permalink to this heading">¶</a></h1>
<section id="submodules">
<h2>Submodules<a class="headerlink" href="#submodules" title="Permalink to this heading">¶</a></h2>
</section>
<section id="module-duHast.Revit.Common.Geometry.curve">
<span id="duhast-revit-common-geometry-curve-module"></span><h2>duHast.Revit.Common.Geometry.curve module<a class="headerlink" href="#module-duHast.Revit.Common.Geometry.curve" title="Permalink to this heading">¶</a></h2>
<section id="revit-curve-helper-functions">
<h3>Revit curve helper functions<a class="headerlink" href="#revit-curve-helper-functions" title="Permalink to this heading">¶</a></h3>
</section>
<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.curve.is_curve_is_within_curve">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.curve.</span></span><span class="sig-name descname"><span class="pre">is_curve_is_within_curve</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">curve_one</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">curve_two</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.curve.is_curve_is_within_curve" title="Permalink to this definition">¶</a></dt>
<dd><p>Checks whether one curve is completely within another curve.</p>
<dl>
<dt>Args:</dt><dd><p>curve_one: The first curve to compare (can be an arc or a line).
curve_two: The second curve to compare (can be an arc or a line).</p>
</dd>
<dt>Returns:</dt><dd><p>The curve that is completely within the other curve, or None if the curves are overlapping.</p>
</dd>
<dt>Example Usage:</dt><dd><p>curve_one = …
curve_two = …
result = check_curve_is_within_curve(curve_one, curve_two)
print(result)</p>
<p>Output:
- If the curves are identical, it will return curve_one.
- If curve_two is completely within curve_one, it will return curve_two.
- If curve_one is completely within curve_two, it will return curve_one.
- If the curves are overlapping, it will return None.</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.curve.calculate_lengthened_curve_geometry">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.curve.</span></span><span class="sig-name descname"><span class="pre">calculate_lengthened_curve_geometry</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">curve_one</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">curve_two</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.curve.calculate_lengthened_curve_geometry" title="Permalink to this definition">¶</a></dt>
<dd><p>Two options when lines are overlapping:</p>
<ul class="simple">
<li><p>extend the longer line to the end of the shorter line not overlapping and delete the shorter line or</p></li>
<li><p>shorten shorter line to move the endpoint currently overlapping to the end point of the longer line, therefore removing the overlap</p></li>
</ul>
<p>First option will shorten number of room separation lines in model. However when multiple lines overlap a single long line this
code will delete a shorter overlapping line still required!</p>
<p>returns two values: first one is the curve to change in length, second one is the curve to delete!</p>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.curve.calculate_shortened_curve_geometry">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.curve.</span></span><span class="sig-name descname"><span class="pre">calculate_shortened_curve_geometry</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">curve_one</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">curve_two</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.curve.calculate_shortened_curve_geometry" title="Permalink to this definition">¶</a></dt>
<dd><p>Two options when lines are overlapping:</p>
<ul class="simple">
<li><p>extend the longer line to the end of the shorter line not overlapping and delete the shorter line or</p></li>
<li><p>shorten shorter line to move the endpoint currently overlapping to the end point of the longer line, therefore removing the overlap</p></li>
</ul>
<p>This is an attempt on option 2</p>
<p>returns the curve of which to change the length!</p>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.curve.modify_model_line_action">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.curve.</span></span><span class="sig-name descname"><span class="pre">modify_model_line_action</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">existing_curve</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">new_curve</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">override_joins</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">True</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.curve.modify_model_line_action" title="Permalink to this definition">¶</a></dt>
<dd><p>Modify the geometry of an existing curve by setting it to a new curve.</p>
<dl class="simple">
<dt>Args:</dt><dd><p>existing_curve (object): The existing curve that needs to be modified.
new_curve (object): The new curve that will replace the existing curve.
override_joins (bool, optional): Flag to indicate whether to override the joins between adjoining model lines. Defaults to True.</p>
</dd>
<dt>Returns:</dt><dd><p>object: An instance of the Result class that contains information about the success or failure of the geometry modification.</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.curve.translate_curves_in_elevation">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.curve.</span></span><span class="sig-name descname"><span class="pre">translate_curves_in_elevation</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">doc</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">original_curves</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">source_elevation</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">target_elevation</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.curve.translate_curves_in_elevation" title="Permalink to this definition">¶</a></dt>
<dd></dd></dl>

</section>
<section id="module-duHast.Revit.Common.Geometry.geometry">
<span id="duhast-revit-common-geometry-geometry-module"></span><h2>duHast.Revit.Common.Geometry.geometry module<a class="headerlink" href="#module-duHast.Revit.Common.Geometry.geometry" title="Permalink to this heading">¶</a></h2>
<section id="revit-geometry-extraction-helper-functions">
<h3>Revit geometry extraction helper functions<a class="headerlink" href="#revit-geometry-extraction-helper-functions" title="Permalink to this heading">¶</a></h3>
</section>
<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_point_as_string">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_point_as_string</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_point_as_string" title="Permalink to this definition">¶</a></dt>
<dd><p>Returns Revit point as a string.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>point</strong> (<em>Autodesk.Revit.DB.XYZ</em>) – A revit point.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>String in format ‘X:Y:Z’</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>str</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_edge_as_string">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_edge_as_string</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_edge_as_string" title="Permalink to this definition">¶</a></dt>
<dd><p>Returns a revit edge as a string.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>edge</strong> (<em>Autodesk.Revit.DB.Edge</em>) – A revit edge.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>String where each row represents a point on the edge.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>str</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.UV_pt_list_from_crv_list">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">UV_pt_list_from_crv_list</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">curve_list</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.UV_pt_list_from_crv_list" title="Permalink to this definition">¶</a></dt>
<dd><p>Returns a list of UV points from a list of curves
:param curve_list: A list of curves
:param type: list
:return: A list of UV points
:rtype: list</p>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.point_in_polygon">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">point_in_polygon</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">polygon</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.point_in_polygon" title="Permalink to this definition">¶</a></dt>
<dd><p>Returns True if a point is inside a polygon, and False if it is not
:param point: The point to check
:type point: list, tuple, or set
:param polygon: The polygon to check
:type polygon: list, tuple, or set
:return: True if the point is inside the polygon, False if it is not
:rtype: bool</p>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.is_close">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">is_close</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">a</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">b</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">rel_tol</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">1e-09</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">abs_tol</span></span><span class="o"><span class="pre">=</span></span><span class="default_value"><span class="pre">0.0</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.is_close" title="Permalink to this definition">¶</a></dt>
<dd><p>Compares two floats with a tolerance. Returns True if they are close enough, otherwise False</p>
<p>refer to: <a class="reference external" href="https://stackoverflow.com/questions/5595425/what-is-the-best-way-to-compare-floats-for-almost-equality-in-python">https://stackoverflow.com/questions/5595425/what-is-the-best-way-to-compare-floats-for-almost-equality-in-python</a></p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>a</strong> (<em>float</em>) – A float</p></li>
<li><p><strong>b</strong> (<em>float</em>) – A float</p></li>
<li><p><strong>rel_tol</strong> (<em>float</em><em>, </em><em>optional</em>) – Relative tolerance used to compare the two floats, defaults to 1e-09</p></li>
<li><p><strong>abs_tol</strong> (<em>float</em><em>, </em><em>optional</em>) – Absolute tolerance used to compare the two floats, defaults to 0.0</p></li>
</ul>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>Returns True if they are close enough to be considered equal, otherwise False</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>bool</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.are_points_identical">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">are_points_identical</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">p1</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">p2</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.are_points_identical" title="Permalink to this definition">¶</a></dt>
<dd><p>Compares the X,Y,Z values of two revit point and returns True if they are the same, otherwise False</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>p1</strong> (<em>Autodesk.Revit.DB.XYZ</em>) – A revit point.</p></li>
<li><p><strong>p2</strong> (<em>Autodesk.Revit.DB.XYZ</em>) – A revit point.</p></li>
</ul>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>True if they are the same, otherwise False.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>bool</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.check_duplicate_point">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">check_duplicate_point</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">points</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.check_duplicate_point" title="Permalink to this definition">¶</a></dt>
<dd><p>Checks whether a collection of points contains another given point and returns True if that is the case.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>points</strong> (<em>list Autodesk.Revit.DB.XYZ</em>) – List of revit points</p></li>
<li><p><strong>point</strong> (<em>Autodesk.Revit.DB.XYZ</em>) – A revit point.</p></li>
</ul>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>True if point is in collection, otherwise False.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>bool</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_point_as_doubles">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_point_as_doubles</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_point_as_doubles" title="Permalink to this definition">¶</a></dt>
<dd><p>Converts a revit XYZ to a list of doubles in order x,y,z.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>point</strong> (<em>Autodesk.Revit.DB.XYZ</em>) – A revit point.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>List of doubles in order of x,y,z</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list double</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.flatten_xyz_point">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">flatten_xyz_point</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">point</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.flatten_xyz_point" title="Permalink to this definition">¶</a></dt>
<dd><p>Flattens a XYZ point to a UV by omitting the Z value of the XYZ.</p>
<p><a class="reference external" href="https://thebuildingcoder.typepad.com/blog/2008/12/2d-polygon-areas-and-outer-loop.html">https://thebuildingcoder.typepad.com/blog/2008/12/2d-polygon-areas-and-outer-loop.html</a></p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>point</strong> (<em>Autodesk.Revit.DB.XYZ</em>) – A revit point.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>A 2D point (UV)</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>Autodesk.Revit.DB.UV</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.flatten_xyz_point_list">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">flatten_xyz_point_list</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">polygon</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.flatten_xyz_point_list" title="Permalink to this definition">¶</a></dt>
<dd><p>Flattens a list of XYZ points to a list of UV points by omitting the Z value of each XYZ.</p>
<p><a class="reference external" href="https://thebuildingcoder.typepad.com/blog/2008/12/2d-polygon-areas-and-outer-loop.html">https://thebuildingcoder.typepad.com/blog/2008/12/2d-polygon-areas-and-outer-loop.html</a></p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>polygon</strong> (<em>list Autodesk.Revit.DB.XYZ</em>) – list of XYZ points</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>list of UV points</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list Autodesk.Revit.DB.UV</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.flatten_xyz_point_list_of_lists">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">flatten_xyz_point_list_of_lists</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">polygons</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.flatten_xyz_point_list_of_lists" title="Permalink to this definition">¶</a></dt>
<dd><p>Flattens a list lists of XYZ points to a list of lists of UV points by omitting the Z value of each XYZ.</p>
<p><a class="reference external" href="https://thebuildingcoder.typepad.com/blog/2008/12/2d-polygon-areas-and-outer-loop.html">https://thebuildingcoder.typepad.com/blog/2008/12/2d-polygon-areas-and-outer-loop.html</a></p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>polygon</strong> (<em>list</em><em> [</em><em>list Autodesk.Revit.DB.XYZ</em><em>]</em>) – list of lists of XYZ points</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>list of lists of UV points</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list [list Autodesk.Revit.DB.UV]</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_coordinate_system_translation_and_rotation">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_coordinate_system_translation_and_rotation</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">doc</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_coordinate_system_translation_and_rotation" title="Permalink to this definition">¶</a></dt>
<dd><p>Returns the rotation as a 3 x 3 matrix and the translation as a 1 x 3 matrix of the shared coordinate system active in document.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>doc</strong> (<em>_type_</em>) – _description_</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>3 x 3 matrix describing rotation, 1 x 3 matrix describing translation</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list (3) [list(3) int], list [int]</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_quadrant">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_quadrant</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">vertex</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">p</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_quadrant" title="Permalink to this definition">¶</a></dt>
<dd><p>Determines the quadrant of a polygon vertex relative to the test point.</p>
<p><a class="reference external" href="https://thebuildingcoder.typepad.com/blog/2010/12/point-in-polygon-containment-algorithm.html">https://thebuildingcoder.typepad.com/blog/2010/12/point-in-polygon-containment-algorithm.html</a></p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>vertex</strong> (<em>Autodesk.Revit.DB.UV</em>) – Revit UV element describing a vertex</p></li>
<li><p><strong>p</strong> (<em>Autodesk.Revit.DB.UV</em>) – Revit UV point</p></li>
</ul>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>An integer of range 0 - 4 describing the quadrant.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>int</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.x_intercept">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">x_intercept</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">p</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">q</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">y</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.x_intercept" title="Permalink to this definition">¶</a></dt>
<dd><p>Determine the X intercept of a polygon edge with a horizontal line at the Y value of the test point.</p>
<p><a class="reference external" href="https://thebuildingcoder.typepad.com/blog/2010/12/point-in-polygon-containment-algorithm.html">https://thebuildingcoder.typepad.com/blog/2010/12/point-in-polygon-containment-algorithm.html</a></p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>p</strong> (<em>Autodesk.Revit.DB.UV</em>) – Revit UV point</p></li>
<li><p><strong>q</strong> (<em>Autodesk.Revit.DB.UV</em>) – Revit UV point</p></li>
<li><p><strong>y</strong> (<em>double</em>) – _description_</p></li>
</ul>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>_description_</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>double</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.adjust_delta">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">adjust_delta</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">delta</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">vertex</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">next_vertex</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">p</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.adjust_delta" title="Permalink to this definition">¶</a></dt>
<dd><p><a class="reference external" href="https://thebuildingcoder.typepad.com/blog/2010/12/point-in-polygon-containment-algorithm.html">https://thebuildingcoder.typepad.com/blog/2010/12/point-in-polygon-containment-algorithm.html</a></p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>delta</strong> (<em>_type_</em>) – _description_</p></li>
<li><p><strong>vertex</strong> (<em>_type_</em>) – _description_</p></li>
<li><p><strong>next_vertex</strong> (<em>_type_</em>) – _description_</p></li>
<li><p><strong>p</strong> (<em>_type_</em>) – _description_</p></li>
</ul>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>_description_</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>_type_</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.is_point_within_polygon">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">is_point_within_polygon</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">polygon</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">point</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.is_point_within_polygon" title="Permalink to this definition">¶</a></dt>
<dd><p>Checks whether a point is within a polygon.</p>
<p><a class="reference external" href="https://thebuildingcoder.typepad.com/blog/2010/12/point-in-polygon-containment-algorithm.html">https://thebuildingcoder.typepad.com/blog/2010/12/point-in-polygon-containment-algorithm.html</a>
odd number of windings rule:
if (angle &amp; 4) return INSIDE else return OUTSIDE
non-zero winding rule:
if (angle != 0) return INSIDE else return OUTSIDE</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>polygon</strong> (<em>list</em><em> of </em><em>Autodesk.Revit.DB.UV</em>) – A polygon</p></li>
<li><p><strong>point</strong> (<em>Autodesk.Revit.DB.UV</em>) – A point</p></li>
</ul>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>Refer winding rules above.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>bool</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_signed_polygon_area">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_signed_polygon_area</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">uv_points</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_signed_polygon_area" title="Permalink to this definition">¶</a></dt>
<dd><p>Calculates the area of a signed UV polygon.</p>
<p><a class="reference external" href="https://thebuildingcoder.typepad.com/blog/2008/12/2d-polygon-areas-and-outer-loop.html">https://thebuildingcoder.typepad.com/blog/2008/12/2d-polygon-areas-and-outer-loop.html</a></p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>uv_points</strong> (<em>list Autodesk.Revit.DB.UV</em>) – list of points defining the polygon.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>The area of the polygon.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>double</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.convert_edge_arrays_into_list_of_points">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">convert_edge_arrays_into_list_of_points</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge_arrays</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.convert_edge_arrays_into_list_of_points" title="Permalink to this definition">¶</a></dt>
<dd><p>Converts an edge array into a list of list of revit XYZ points.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>edge_arrays</strong> (<em>Autodesk.Revit.DB.EdgeArrayArray</em><em> ( </em><em>no not a spelling mistake :</em><em>) </em><em>)</em>) – A revit edge array.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>A List of list of revit XYZ points.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list of list Autodesk.Revit.DB.XYZ</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_edge_points">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_edge_points</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_edge_points" title="Permalink to this definition">¶</a></dt>
<dd><p>Retrieves the revit XYZ points defining an edge (curves get tessellated!)</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>edge</strong> (<em>Autodesk.Revit.DB.Edge</em>) – An edge of a solid.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>A list of revit XYZ points.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list Autodesk.Revit.DB.XYZ</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.check_duplicate_edge">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">check_duplicate_edge</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edges</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">edge</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.check_duplicate_edge" title="Permalink to this definition">¶</a></dt>
<dd><p>Checks whether a collection contains a given edge and returns True if that is the case.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>edges</strong> (<em>list</em><em> of </em><em>Autodesk.Revit.DB.Edge</em>) – List of edges toi check against.</p></li>
<li><p><strong>edge</strong> (<em>Autodesk.Revit.DB.Edge</em>) – An edge</p></li>
</ul>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>True if edge is already in collection, otherwise False.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>bool</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.check_solid_is_zero_height">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">check_solid_is_zero_height</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">solid</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.check_solid_is_zero_height" title="Permalink to this definition">¶</a></dt>
<dd><p>Checks if points making up a solid have multiple Z values.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>solid</strong> (<em>Autodesk.Revit.DB.Solid</em>) – A revit solid object.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>False if points collection of a solid has multiple z values, True if only one Z value in points collection (2D solid…??)</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>bool</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.check_edges_are_zero_height">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">check_edges_are_zero_height</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edges</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.check_edges_are_zero_height" title="Permalink to this definition">¶</a></dt>
<dd><p>Checks if points making up a edges have multiple Z values.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>edges</strong> (<em>list Autodesk.Revit.DB.Edge</em>) – A list of edges.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>False if points collection of a edges has multiple z values, True if only one Z value in points collection (2D edges…??)</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>bool</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_lowest_z_from_solid">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_lowest_z_from_solid</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">solid</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_lowest_z_from_solid" title="Permalink to this definition">¶</a></dt>
<dd><p>Gets the lowest Z value in a solids point collection.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>solid</strong> (<em>Autodesk.Revit.DB.Solid</em>) – A solid.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>The lowest Z value of any point in the solids vertex collection.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>double</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_lowest_z_from_edges_point_collection">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_lowest_z_from_edges_point_collection</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edges</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_lowest_z_from_edges_point_collection" title="Permalink to this definition">¶</a></dt>
<dd><p>Gets the lowest Z value in a edges collection</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>edges</strong> (<em>list Autodesk.Revit.DB.Edge</em>) – A list of edges.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>The lowest Z value of any point in the edges vertex collection.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>double</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.edges_are_connected">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">edges_are_connected</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">edge1</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">edge2</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.edges_are_connected" title="Permalink to this definition">¶</a></dt>
<dd><p>Checks whether edges are connected by comparing their points. If there is an identical point in both        then they are connected.</p>
<p>Revit solids dont have crossing edges!</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>edge1</strong> (<em>Autodesk.Revit.DB.Edge</em>) – An edge.</p></li>
<li><p><strong>edge2</strong> (<em>Autodesk.Revit.DB.Edge</em>) – Another edge.</p></li>
</ul>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>_description_</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>bool</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_faces_sorted_by_area_from_solid">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_faces_sorted_by_area_from_solid</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">solid</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_faces_sorted_by_area_from_solid" title="Permalink to this definition">¶</a></dt>
<dd><p>Returns all faces from a solid sorted descending from biggest to smallest by area.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>solid</strong> (<em>Autodesk.Revit.DB.Solid</em>) – A solid.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>A list of faces, sorted biggest to smallest by area.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list Autodesk.Revit.DB.Face</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.pair_faces_by_area">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">pair_faces_by_area</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">faces</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.pair_faces_by_area" title="Permalink to this definition">¶</a></dt>
<dd><p>Returns a list of lists of face pairs, where a nested list contains faces with the same measured area.</p>
<p>Sample would be a ceiling solid. The top and bottom face of that ceiling would be an area pair.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>faces</strong> (<em>list Autodesk.Revit.DB.Face</em>) – A list of faces.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>A list of lists of faces.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list of list Autodesk.Revit.DB.Face</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_faces_with_lowest_z_from_pairs">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_faces_with_lowest_z_from_pairs</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">face_pairs</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_faces_with_lowest_z_from_pairs" title="Permalink to this definition">¶</a></dt>
<dd><p>Gets the face with the lowest Z value from list of faces.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>face_pairs</strong> (<em>list</em><em> of </em><em>list Autodesk.Revit.DB.Face</em>) – A list of lists of face pairs, where a nested list contains faces with the same measured area.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>A list of faces.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list Autodesk.Revit.DB.Face</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.get_unique_horizontal_faces">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">get_unique_horizontal_faces</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">faces</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.get_unique_horizontal_faces" title="Permalink to this definition">¶</a></dt>
<dd><p>Filters out any horizontal faces from list of faces past in.</p>
<p>Will also further filter by: faces with the same area only the face with the lower Z value will be returned.
Note: works only on planar faces</p>
<p>TODO: It could be way simpler just to check for the face with a negative face normal Z value…</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>faces</strong> (<em>list Autodesk.Revit.DB.Face</em>) – A list of faces.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>A list of faces.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list Autodesk.Revit.DB.Face</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.is_loop_within_other_loop_but_not_reference_loops">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">is_loop_within_other_loop_but_not_reference_loops</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">exterior_loop</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">other_loop</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">hole_loops</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.is_loop_within_other_loop_but_not_reference_loops" title="Permalink to this definition">¶</a></dt>
<dd><p>Checks whether any of the other loops is within the exterior loop and if so        if it is not also within one of the holeLoops …that would be an island</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>exterior_loop</strong> (<em>list</em><em> of </em><em>Autodesk.Revit.DB.UV</em>) – A polygon loop describing the external boundary of a face.</p></li>
<li><p><strong>other_loop</strong> (<em>list</em><em> of </em><em>Autodesk.Revit.DB.UV</em>) – A polygon loop which is to be checked as to whether it is within the exterior loop and the any hole loops.</p></li>
<li><p><strong>hole_loops</strong> (<em>namedtuple</em><em>(</em><em>'uvLoop'</em><em>, </em><em>'loop area id threeDPoly'</em><em>)        </em><em>.Loop is a list</em><em> of </em><em>UV points defining a polygon loop
.area is a double describing the polygon area
.id is an integer
.threeDPoly is an edge loop</em>) – A list of named tuples containing .loop property which is a list of UV points forming a polygon which have been identified         as creating a hole in the exteriorLoop.</p></li>
</ul>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>True if within exterior loop but not within hole loops, otherwise False.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>bool</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.build_loops_dictionary">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">build_loops_dictionary</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">loops</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.build_loops_dictionary" title="Permalink to this definition">¶</a></dt>
<dd><p>Will return a dic where:</p>
<ul class="simple">
<li><p>key is the outer loop of a polygon id</p></li>
<li><p>values is a list of tuples describing holes in the key polygon</p></li>
</ul>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>loops</strong> (<em>list</em><em>[</em><em>namedtuple</em><em>(</em><em>'uvLoop'</em><em>, </em><em>'loop area id threeDPoly'</em><em>)</em><em>]</em>) – A list of named tuples describing polygons.        .Loop is a list of UV points defining a polygon loop
.area is a double describing the polygon area
.id is an integer
.threeDPoly is an edge loop</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>A dictionary.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>dic {int: list[namedtuple(‘uvLoop’, ‘loop area id threeDPoly’)]}</p>
</dd>
</dl>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.negate_vector">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">negate_vector</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">vector</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.negate_vector" title="Permalink to this definition">¶</a></dt>
<dd><p>Negates the direction of a given vector
:param vector: The vector to negate
:type vector: list or tuple
:return: The negated vector
:rtype: list</p>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.sort_points_by_min_and_max">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">sort_points_by_min_and_max</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">min_pt</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">max_pt</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.sort_points_by_min_and_max" title="Permalink to this definition">¶</a></dt>
<dd><p>Takes BoundingBox or Outline Min and Max points and
returns the true Min and Max points. This is to ensure
no zero thickness geometries are created.
:param min_pt: The minimum point
:type min_pt: XYZ
:param max_pt: The maximum point
:type max_pt: XYZ
:return: The sorted points
:rtype: tuple</p>
</dd></dl>

<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.geometry.transform_point_by_elem_transform">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.geometry.</span></span><span class="sig-name descname"><span class="pre">transform_point_by_elem_transform</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">pt</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">transform</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.geometry.transform_point_by_elem_transform" title="Permalink to this definition">¶</a></dt>
<dd><p>Transforms a point by an element transform
:param pt: The point to transform
:type pt: XYZ
:param transform: The transform to use
:type transform: Transform
:return: The transformed point
:rtype: XYZ</p>
</dd></dl>

</section>
<section id="module-duHast.Revit.Common.Geometry.solids">
<span id="duhast-revit-common-geometry-solids-module"></span><h2>duHast.Revit.Common.Geometry.solids module<a class="headerlink" href="#module-duHast.Revit.Common.Geometry.solids" title="Permalink to this heading">¶</a></h2>
<section id="revit-solids-helper-functions">
<h3>Revit solids helper functions<a class="headerlink" href="#revit-solids-helper-functions" title="Permalink to this heading">¶</a></h3>
</section>
<dl class="py function">
<dt class="sig sig-object py" id="duHast.Revit.Common.Geometry.solids.get_2d_points_from_solid">
<span class="sig-prename descclassname"><span class="pre">duHast.Revit.Common.Geometry.solids.</span></span><span class="sig-name descname"><span class="pre">get_2d_points_from_solid</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">element</span></span></em><span class="sig-paren">)</span><a class="headerlink" href="#duHast.Revit.Common.Geometry.solids.get_2d_points_from_solid" title="Permalink to this definition">¶</a></dt>
<dd><p>Returns a list of lists of data geometry instances representing the flattened (2D geometry) of the Element
List of Lists because an element can be made up of multiple solids. Each nested list represents one element solid.
Does not work with in place elements.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><p><strong>element</strong> (<em>Autodesk.Revit.DB.Element</em>) – A revit element instance.</p>
</dd>
<dt class="field-even">Returns<span class="colon">:</span></dt>
<dd class="field-even"><p>A list of data geometry instances.</p>
</dd>
<dt class="field-odd">Return type<span class="colon">:</span></dt>
<dd class="field-odd"><p>list of <code class="xref py py-class docutils literal notranslate"><span class="pre">DataGeometry</span></code></p>
</dd>
</dl>
</dd></dl>

</section>
<section id="module-duHast.Revit.Common.Geometry">
<span id="module-contents"></span><h2>Module contents<a class="headerlink" href="#module-duHast.Revit.Common.Geometry" title="Permalink to this heading">¶</a></h2>
</section>
</section>


          </div> 
        </div>
      </div>
    <div class="footer">
    <p>
      &copy; Copyright 2023, Jan Christel.
      Created using <a href="http://www.sphinx-doc.org/">Sphinx</a> 7.0.1 <a href="https://github.com/mga-sphinx/sphinx_adc_theme">ADC Theme</a> .
    (Revision )
        </p>
    </div>
      <div class="clearer"></div>
    </div>
        <div id="breadcrumbs">
                <a href="modules.html" accesskey="U">duHast</a><img src="../_static/img/triangle_closed.png" height="9" width="9" alt="&gt;">
                <a href="duHast.html" >duHast package</a><img src="../_static/img/triangle_closed.png" height="9" width="9" alt="&gt;">
                <a href="duHast.Revit.html" >duHast.Revit package</a><img src="../_static/img/triangle_closed.png" height="9" width="9" alt="&gt;">
                <a href="duHast.Revit.Common.html" >duHast.Revit.Common package</a><img src="../_static/img/triangle_closed.png" height="9" width="9" alt="&gt;">
                duHast.Revit.Common.Geometry package
        </div>
        <script type="text/javascript" charset="utf-8" src="../_static/js/toc.js"></script>
  </body>
</html>